# Generated by Django 5.0.3 on 2024-04-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='image_url',
            field=models.URLField(default='/static/8cbad94afb0bd6bd235cdc917a9c7f83.jpg'),
        ),
    ]
