# Generated by Django 5.0.3 on 2024-04-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_manga_image_url_alter_manga_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
