# Generated by Django 5.0.3 on 2024-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_manga_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manga_images/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
